### PR TITLE
Fix watch and update Service Nodeport Bug and  resolved #96 alameda-aiDep's template containers ports 

### LINKED ISSUE #96: alameda-ai does not need 50051 port since it does not play as a server
https://github.com/containers-ai/federatorai-operator/blob/2bd35102d0c85ef7bcd60c3ab0f8209287a5f4a3/assets/Deployment/alameda-aiDM.yaml#L26

alameda-ai does not need 50051 port since it does not play as a server

### PR DESCRIPTION
**Pull request by ekko771**

### CODE REVIEW

File: pkg/controller/alamedaservice/alamedaservice_controller.go [hunk 1]
```diff
@@ -392,9 +392,13 @@ func (r *ReconcileAlamedaService) syncService(instance *federatoraiv1alpha1.Alam
 		} else {
 			if updateresource.MisMatchResourceService(foundSV, resourceSV) {
 				log.Info("Update Resource Service:", "foundSV.Name", foundSV.Name)
```
Comment (mamafun) [inline pkg/controller/alamedaservice/alamedaservice_controller.go]: Should me change the message from "Update Resource Service" to "Delete Resource Service"?

File: pkg/controller/alamedaservice/alamedaservice_controller.go [hunk 2]
```diff
@@ -392,9 +392,13 @@ func (r *ReconcileAlamedaService) syncService(instance *federatoraiv1alpha1.Alam
...
 				if err != nil {
-					return errors.Errorf("update service %s/%s failed: %s", foundSV.Namespace, foundSV.Name, err.Error())
+					return errors.Errorf("delete service %s/%s failed: %s", foundSV.Namespace, foundSV.Name, err.Error())
+				}
+				err = r.client.Create(context.TODO(), resourceSV)
+				if err != nil {
+					return errors.Errorf("create service %s/%s failed: %s", foundSV.Namespace, foundSV.Name, err.Error())
 				}
 				log.Info("Successfully Update Resource Service", "resourceSV.Name", foundSV.Name)
 			}
```
Comment (mamafun) [inline pkg/controller/alamedaservice/alamedaservice_controller.go]: same thing as above comment
